language: go

go:
    - 1.4

install: true

script:
    - go get -v -u github.com/rubenv/broadcaster
    - npm install -g grunt-cli bower
    - bower install
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install
    - npm test
